Traceback (most recent call last):
  File "/g/data3/w48/dm5220/scripts/um2nc/convert_um2nc.py", line 30, in <module>
    os.makedirs(output_folder,exist_ok=True)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.10/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/g/data/w48/dm5220/data/vacba'
